version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app/frontend
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/install_environment_dependencies.sh
      timeout: 400
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: webapp
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: webapp
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: webapp
